### ISSUE TITLE
Issue with citations.bib when pip installing into Qiime2 (with solution)

### ISSUE THREAD

**Issue by adswafford** [cameronmartino/gemelli#21]
After installing gemellie in my Qiime2 2019.7 environment via the following commands, I got the error message below:
Steps to reproduce:
 conda activate qiime2-2019.7
 pip install gemelli
 qiime gemelli --help
QIIME is caching your current deployment for improved performance. This may take a few moments and should only happen once per deployment.
Traceback (most recent call last):
  File "/home/adswafford/miniconda3/envs/qiime2-2019.7/bin/qiime", line 11, in <module>
    sys.exit(qiime())
  File "/home/adswafford/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/adswafford/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/adswafford/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/click/core.py", line 1132, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/home/adswafford/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/click/core.py", line 1171, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/home/adswafford/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/q2cli/commands.py", line 101, in get_command
    plugin = self._plugin_lookup[name]
  File "/home/adswafford/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/q2cli/commands.py", line 77, in _plugin_lookup
    import q2cli.core.cache
  File "/home/adswafford/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/q2cli/core/cache.py", line 403, in <module>
    CACHE = DeploymentCache()
  File "/home/adswafford/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/q2cli/core/cache.py", line 61, in __init__
    self._state = self._get_cached_state(refresh=refresh)
  File "/home/adswafford/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/q2cli/core/cache.py", line 107, in _get_cached_state
    self._cache_current_state(current_requirements)
  File "/home/adswafford/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/q2cli/core/cache.py", line 200, in _cache_current_state
    state = self._get_current_state()
  File "/home/adswafford/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/q2cli/core/cache.py", line 238, in _get_current_state
    plugin_manager = qiime2.sdk.PluginManager()
  File "/home/adswafford/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/qiime2/sdk/plugin_manager.py", line 44, in __new__
    self._init()
  File "/home/adswafford/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/qiime2/sdk/plugin_manager.py", line 59, in _init
    plugin = entry_point.load()
  File "/home/adswafford/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2322, in load
    return self.resolve()
  File "/home/adswafford/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2328, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/adswafford/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/gemelli/q2/plugin_setup.py", line 50, in <module>
    'citations.bib', package='gemelli')
  File "/home/adswafford/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/qiime2/core/cite.py", line 30, in load
    with open(path) as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/adswafford/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/gemelli/citations.bib'

The solution was to do:
wget -P /home/adswafford/miniconda3/envs/qiime2-2019.7/lib/python3.6/site-packages/gemelli/ https://raw.githubusercontent.com/cameronmartino/gemelli/master/gemelli/citations.bib

**Comment by cameronmartino** [comment]
Thanks for reporting. Looks like the pypi build missed the citations in the upload for some reason.

**Comment by cameronmartino** [comment]
Verified on a fresh env that this is patched, just be sure to install gemelli v0.0.4 or greater. Thanks for reporting! Feel free to reopen the issue if the patch in v0.0.4 does not work for you.
